"""
Generate all publication-quality figures for the Results section.

Produces Figures 1–6 for the main manuscript targeting ACS Energy & Fuels.
Uses pre-computed data from system/data/ and contour_results.pkl so that
the full BioSTEAM simulation does not need to re-run.

Pareto scatter figures (Figs 2–3) are copied from pre-computed images
generated by system/pareto_scatter.py.  To regenerate them from scratch,
run ``python3.12 -m system.pareto_scatter`` first.

Run from the project root:
    python3.12 -m system.generate_figures
"""

import os
import shutil
import sys
import warnings

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import SymLogNorm, LogNorm

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from system._plot_style import (
    apply_style, COLORS, LINE_STYLES, MARKERS,
    CMAP_SEQ, CMAP_DIV, savefig, figsize, label_panels,
)

apply_style()

_DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
_SYS_DIR = os.path.dirname(__file__)
_FIG_DIR = os.path.join(_SYS_DIR, "report", "figures")
os.makedirs(_FIG_DIR, exist_ok=True)


# ============================================================================
# Figure 1 — ML parity plots (8-panel composite)
# ============================================================================
def fig1_parity_composite():
    """8-panel parity plot: predicted vs experimental for each output."""
    df = pd.read_csv(os.path.join(_DATA_DIR, "parity_actual_vs_predicted_test_set.csv"))
    metrics = pd.read_csv(
        os.path.join(_DATA_DIR, "model_test_metrics_per_output.csv"),
        index_col=0,
    )

    outputs = [
        "Liquid", "Gas", "Solid", "Gasoline range hydrocarbons",
        "Diesel range hydrocarbons", "Total aromatics (w%)",
        "BTX (w%)", "Wax (>C21)",
    ]
    short = {
        "Liquid": "Liquid",
        "Gas": "Gas",
        "Solid": "Solid",
        "Gasoline range hydrocarbons": "Gasoline-range",
        "Diesel range hydrocarbons": "Diesel-range",
        "Total aromatics (w%)": "Total aromatics",
        "BTX (w%)": "BTX",
        "Wax (>C21)": "Wax (>C21)",
    }

    fig, axes = plt.subplots(2, 4, figsize=(7.0, 4.0))
    axes_flat = axes.ravel()

    for i, out in enumerate(outputs):
        ax = axes_flat[i]
        sub = df[df["Output"] == out]
        act = sub["Actual_wt%"].values
        pred = sub["Predicted_wt%"].values

        ax.scatter(act, pred, s=15, alpha=0.6, color=COLORS[0],
                   edgecolors="k", linewidths=0.3)

        lo = min(act.min(), pred.min(), 0)
        hi = max(act.max(), pred.max()) * 1.05
        ax.plot([lo, hi], [lo, hi], ls="--", color="gray", lw=0.8)
        ax.set_xlim(lo, hi)
        ax.set_ylim(lo, hi)

        r2 = metrics.loc[out, "R2"]
        mae = metrics.loc[out, "MAE"]
        ax.text(
            0.05, 0.92,
            f"R² = {r2:.2f}\nMAE = {mae:.1f}",
            transform=ax.transAxes, fontsize=6,
            va="top", ha="left",
            bbox=dict(boxstyle="round,pad=0.2", fc="white", alpha=0.8, lw=0.3),
        )

        ax.set_title(short[out], fontsize=7)
        if i >= 4:
            ax.set_xlabel("Experimental (wt %)")
        if i % 4 == 0:
            ax.set_ylabel("Predicted (wt %)")

    label_panels(axes_flat)
    fig.tight_layout(h_pad=1.0, w_pad=0.5)
    savefig(fig, os.path.join(_FIG_DIR, "fig1_parity_composite"))
    print("  → fig1_parity_composite.pdf / .png")
    plt.close(fig)


# ============================================================================
# Figure 2 — Pareto scatter (baseline) — copy from pre-computed
# ============================================================================
def fig2_pareto_baseline():
    """Copy pre-computed baseline Pareto scatter into report/figures/.

    The source images are generated by ``python3.12 -m system.pareto_scatter``.
    """
    for ext in ("png", "pdf"):
        src = os.path.join(_SYS_DIR, f"pareto_scatter_baseline.{ext}")
        dst = os.path.join(_FIG_DIR, f"fig2_pareto_baseline.{ext}")
        if os.path.exists(src):
            shutil.copy2(src, dst)
        else:
            print(f"  [WARN] {src} not found — run system.pareto_scatter first")
    print("  → fig2_pareto_baseline.pdf / .png  (copied)")


# ============================================================================
# Figure 3 — Pareto scatter (all scenarios) — copy from pre-computed
# ============================================================================
def fig3_pareto_all_scenarios():
    """Copy pre-computed multi-scenario Pareto scatter into report/figures/.

    The source images are generated by ``python3.12 -m system.pareto_scatter``.
    """
    for ext in ("png", "pdf"):
        src = os.path.join(_SYS_DIR, f"pareto_scatter_by_scenario.{ext}")
        dst = os.path.join(_FIG_DIR, f"fig3_pareto_all_scenarios.{ext}")
        if os.path.exists(src):
            shutil.copy2(src, dst)
        else:
            print(f"  [WARN] {src} not found — run system.pareto_scatter first")
    print("  → fig3_pareto_all_scenarios.pdf / .png  (copied)")


# ============================================================================
# Figure 4 — Revenue breakdown by product group (stacked bar)
# ============================================================================
def fig4_revenue_breakdown():
    """Stacked bar chart of annual revenue by product group × scenario."""
    # Data from documented optimal_scenarios.md results
    scenarios = ["baseline", "high_fuel", "high_chem", "high_organics"]
    labels = ["Baseline", "High fuel", "High chem.", "High organics"]
    groups = ["Fuels", "Chemicals", "Organics", "Hydrogen"]
    data = {
        "Fuels":     [18.68, 27.37, 10.16,  6.16],
        "Chemicals": [ 5.96,  2.91,  7.41,  0.54],
        "Organics":  [16.57, 16.26, 16.19, 92.49],
        "Hydrogen":  [ 4.12,  1.65,  1.65,  1.65],
    }
    colors_bar = [COLORS[0], COLORS[1], COLORS[2], COLORS[3]]

    x = np.arange(len(scenarios))
    width = 0.6

    fig, ax = plt.subplots(figsize=figsize("single"))
    bottom = np.zeros(len(scenarios))
    for j, grp in enumerate(groups):
        vals = np.array(data[grp])
        bars = ax.bar(x, vals, width, bottom=bottom, label=grp,
                       color=colors_bar[j], edgecolor="white", linewidth=0.4)
        # Label bars > $5 M
        for k, (v, b) in enumerate(zip(vals, bottom)):
            if v > 5:
                ax.text(x[k], b + v / 2, f"${v:.0f}M",
                        ha="center", va="center", fontsize=5.5, color="white",
                        fontweight="bold")
        bottom += vals

    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=7)
    ax.set_ylabel("Annual revenue ($ M yr⁻¹)")
    ax.legend(loc="upper left", fontsize=6, ncol=2)

    savefig(fig, os.path.join(_FIG_DIR, "fig4_revenue_breakdown"))
    print("  → fig4_revenue_breakdown.pdf / .png")
    plt.close(fig)


# ============================================================================
# Figure 5 — Sensitivity contour plots (6 key pairs × 3 objectives)
# ============================================================================
def fig5_contours():
    """Contour subplots from pre-computed contour_results.pkl."""
    import pickle

    pkl_path = os.path.join(_PROJECT_ROOT, "contour_results.pkl")
    if not os.path.exists(pkl_path):
        print("  [SKIP] contour_results.pkl not found — run system.contours first.")
        return

    with open(pkl_path, "rb") as f:
        results = pickle.load(f)

    axis_labels = {
        "split_TOD": "CP + TOD fraction (x₁)",
        "split_CP": "TOD fraction (x₂)",
        "split_CPY": "CPY fraction (x₃)",
        "split_PLASMA": "PLASMA fraction",
        "split_HC": "HC fraction (x₄)",
    }

    # Select 6 key pairs (drop redundant PLASMA pairs since PLASMA = 1-CPY)
    key_pairs = [
        "split_TOD vs split_CP",
        "split_TOD vs split_CPY",
        "split_TOD vs split_HC",
        "split_CP vs split_CPY",
        "split_CP vs split_HC",
        "split_CPY vs split_HC",
    ]
    pairs = {k: results[k] for k in key_pairs if k in results}
    n_pairs = len(pairs)

    fig, axes = plt.subplots(n_pairs, 3, figsize=(7.0, 2.2 * n_pairs))
    if n_pairs == 1:
        axes = axes[np.newaxis, :]

    for row, (key, data) in enumerate(pairs.items()):
        X, Y = np.meshgrid(data["x_vals"], data["y_vals"])
        x_label = axis_labels.get(data["x_name"], data["x_name"])
        y_label = axis_labels.get(data["y_name"], data["y_name"])

        # MSP
        ax = axes[row, 0]
        cf = ax.contourf(X, Y, data["MSP"], levels=15, cmap=CMAP_DIV)
        ax.contour(X, Y, data["MSP"], levels=15, colors="k", linewidths=0.4)
        fig.colorbar(cf, ax=ax, label="MSP ($ kg⁻¹ feed)")
        ax.set_xlabel(x_label)
        ax.set_ylabel(y_label)
        if row == 0:
            ax.set_title("MSP", fontsize=8)

        # GWP
        ax = axes[row, 1]
        cf = ax.contourf(X, Y, data["GWP"], levels=15, cmap=CMAP_SEQ)
        ax.contour(X, Y, data["GWP"], levels=15, colors="k", linewidths=0.4)
        fig.colorbar(cf, ax=ax, label=r"GWP (kg CO$_2$-eq kg⁻¹)")
        ax.set_xlabel(x_label)
        ax.set_ylabel(y_label)
        if row == 0:
            ax.set_title("GWP", fontsize=8)

        # CAC
        ax = axes[row, 2]
        cac = data["CAC"]
        if np.all(np.isnan(cac)):
            ax.text(0.5, 0.5, "No finite\nCAC values", transform=ax.transAxes,
                    ha="center", va="center", fontsize=7)
        else:
            cac_f = cac[np.isfinite(cac)]
            has_neg = np.any(cac_f < 0)
            if has_neg:
                abs_max = np.nanmax(np.abs(cac_f))
                abs_pos = cac_f[cac_f > 0]
                linthresh = np.nanmin(abs_pos) if len(abs_pos) > 0 else 1.0
                norm = SymLogNorm(linthresh=linthresh, vmin=-abs_max, vmax=abs_max)
                cf = ax.contourf(X, Y, cac, levels=15, cmap="RdBu_r", norm=norm)
                ax.contour(X, Y, cac, levels=15, colors="k", linewidths=0.4,
                           norm=norm)
            else:
                vmin = np.nanmin(cac_f[cac_f > 0])
                vmax = np.nanmax(cac_f)
                norm = LogNorm(vmin=vmin, vmax=vmax)
                cf = ax.contourf(X, Y, cac, levels=np.geomspace(vmin, vmax, 15),
                                 cmap="plasma", norm=norm)
                ax.contour(X, Y, cac, levels=np.geomspace(vmin, vmax, 15),
                           colors="k", linewidths=0.4, norm=norm)
            fig.colorbar(cf, ax=ax, label=r"CAC ($ kg⁻¹ CO$_2$-eq)")
        ax.set_xlabel(x_label)
        ax.set_ylabel(y_label)
        if row == 0:
            ax.set_title("CAC", fontsize=8)

    label_panels(axes.ravel())
    fig.tight_layout()
    savefig(fig, os.path.join(_FIG_DIR, "fig5_contours"))
    print("  → fig5_contours.pdf / .png")
    plt.close(fig)


# ============================================================================
# Figure 6 — Literature comparison (MSP and GWP vs published studies)
# ============================================================================
def fig6_literature_comparison():
    """Side-by-side comparison of this work vs literature values.

    Literature MSP and GWP data from published waste-plastic pyrolysis
    TEA/LCA studies cited in the manuscript.
    """
    # ── Literature data ────────────────────────────────────────────────
    # Source                                    MSP ($/kg feed)   GWP (kg CO2-eq/kg feed)
    # Dang et al. 2016  [10]                    +0.12             –0.18
    # Westerhout et al. 1998  [11]              +0.25             n/a
    # Yadav et al. 2022  [18]                   +0.08             –0.12
    # Jeswani et al. 2021  [19]                 n/a               –0.28
    # Meys et al. 2021  [20]                    n/a               –0.10
    lit = [
        {"label": "Dang et al.\n(2016)",       "MSP":  0.12, "GWP": -0.18},
        {"label": "Westerhout et al.\n(1998)", "MSP":  0.25, "GWP":  np.nan},
        {"label": "Yadav et al.\n(2022)",      "MSP":  0.08, "GWP": -0.12},
        {"label": "Jeswani et al.\n(2021)",    "MSP":  np.nan, "GWP": -0.28},
        {"label": "Meys et al.\n(2021)",       "MSP":  np.nan, "GWP": -0.10},
    ]

    # ── This work (documented optimal results) ────────────────────────
    this_work = [
        {"label": "This work\n(baseline)",       "MSP": -0.524, "GWP": -0.315},
        {"label": "This work\n(high organics)",  "MSP":  0.009, "GWP": -0.876},
    ]

    # ── Panel (a): MSP comparison ─────────────────────────────────────
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=figsize("double", aspect=0.45))

    # Collect MSP entries
    msp_labels, msp_vals, msp_colors = [], [], []
    for d in lit:
        if np.isfinite(d["MSP"]):
            msp_labels.append(d["label"])
            msp_vals.append(d["MSP"])
            msp_colors.append(COLORS[0])
    for d in this_work:
        if np.isfinite(d["MSP"]):
            msp_labels.append(d["label"])
            msp_vals.append(d["MSP"])
            msp_colors.append(COLORS[1])

    y_pos = np.arange(len(msp_labels))
    bars1 = ax1.barh(y_pos, msp_vals, color=msp_colors, edgecolor="white",
                      linewidth=0.4, height=0.6)
    ax1.set_yticks(y_pos)
    ax1.set_yticklabels(msp_labels, fontsize=6.5)
    ax1.set_xlabel("MSP ($ kg⁻¹ feed)")
    ax1.axvline(0, color="k", lw=0.5, ls="-")
    ax1.invert_yaxis()
    # Value labels
    for bar, val in zip(bars1, msp_vals):
        offset = 0.02 if val >= 0 else -0.02
        ha = "left" if val >= 0 else "right"
        ax1.text(val + offset, bar.get_y() + bar.get_height() / 2,
                 f"{val:+.3f}", va="center", ha=ha, fontsize=6)

    # ── Panel (b): GWP comparison ─────────────────────────────────────
    gwp_labels, gwp_vals, gwp_colors = [], [], []
    for d in lit:
        if np.isfinite(d["GWP"]):
            gwp_labels.append(d["label"])
            gwp_vals.append(d["GWP"])
            gwp_colors.append(COLORS[0])
    for d in this_work:
        if np.isfinite(d["GWP"]):
            gwp_labels.append(d["label"])
            gwp_vals.append(d["GWP"])
            gwp_colors.append(COLORS[1])

    y_pos2 = np.arange(len(gwp_labels))
    bars2 = ax2.barh(y_pos2, gwp_vals, color=gwp_colors, edgecolor="white",
                      linewidth=0.4, height=0.6)
    ax2.set_yticks(y_pos2)
    ax2.set_yticklabels(gwp_labels, fontsize=6.5)
    ax2.set_xlabel(r"GWP (kg CO$_2$-eq kg⁻¹ feed)")
    ax2.axvline(0, color="k", lw=0.5, ls="-")
    ax2.invert_yaxis()
    for bar, val in zip(bars2, gwp_vals):
        offset = 0.02 if val >= 0 else -0.02
        ha = "left" if val >= 0 else "right"
        ax2.text(val + offset, bar.get_y() + bar.get_height() / 2,
                 f"{val:.3f}", va="center", ha=ha, fontsize=6)

    # Legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor=COLORS[0], edgecolor="white", label="Literature"),
        Patch(facecolor=COLORS[1], edgecolor="white", label="This work"),
    ]
    ax1.legend(handles=legend_elements, loc="lower right", fontsize=6)

    label_panels([ax1, ax2])
    fig.tight_layout()
    savefig(fig, os.path.join(_FIG_DIR, "fig6_literature_comparison"))
    print("  → fig6_literature_comparison.pdf / .png")
    plt.close(fig)


# ============================================================================
# Main
# ============================================================================
if __name__ == "__main__":
    print("Generating publication figures …\n")

    print("[1/6] ML parity composite")
    fig1_parity_composite()

    print("[2/6] Pareto scatter — baseline")
    fig2_pareto_baseline()

    print("[3/6] Pareto scatter — all scenarios")
    fig3_pareto_all_scenarios()

    print("[4/6] Revenue breakdown")
    fig4_revenue_breakdown()

    print("[5/6] Sensitivity contours")
    fig5_contours()

    print("[6/6] Literature comparison")
    fig6_literature_comparison()

    print(f"\nAll figures saved to {_FIG_DIR}/")
